name: frontend
description: A Flutter app that detects driver status using AI.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Required packages
  http: ^0.13.6
  image_picker: ^1.0.0
  shared_preferences: ^2.0.15
  sensors_plus: ^2.0.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
